#!/usr/bin/env ruby
# encoding: UTF-8
# 2012/03/07-

require 'rubygems'
ENV['BUNDLE_GEMFILE'] = File.join(File.dirname(__FILE__), '..', 'Gemfile')
require 'bundler/setup'
require 'test-unit'
exit Test::Unit::AutoRunner.run(true)
