# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jdbc-helper"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Junegunn Choi"]
  s.date = "2012-02-02"
  s.description = "A JDBC helper for JRuby/Database developers."
  s.email = "junegunn.c@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "lib/jdbc-helper.rb",
    "lib/jdbc-helper/connection.rb",
    "lib/jdbc-helper/connection/callable_statement.rb",
    "lib/jdbc-helper/connection/parameterized_statement.rb",
    "lib/jdbc-helper/connection/prepared_statement.rb",
    "lib/jdbc-helper/connection/result_set_enumerator.rb",
    "lib/jdbc-helper/connection/row.rb",
    "lib/jdbc-helper/connection/statement_pool.rb",
    "lib/jdbc-helper/connection/type_map.rb",
    "lib/jdbc-helper/connector.rb",
    "lib/jdbc-helper/connector/mysql_connector.rb",
    "lib/jdbc-helper/connector/oracle_connector.rb",
    "lib/jdbc-helper/connector/postgres_connector.rb",
    "lib/jdbc-helper/connector/sql_server_connector.rb",
    "lib/jdbc-helper/constants.rb",
    "lib/jdbc-helper/sql/expression.rb",
    "lib/jdbc-helper/sql/sql.rb",
    "lib/jdbc-helper/sql/sql_prepared.rb",
    "lib/jdbc-helper/wrapper/function_wrapper.rb",
    "lib/jdbc-helper/wrapper/object_wrapper.rb",
    "lib/jdbc-helper/wrapper/procedure_wrapper.rb",
    "lib/jdbc-helper/wrapper/sequence_wrapper.rb",
    "lib/jdbc-helper/wrapper/table_wrapper.rb"
  ]
  s.homepage = "http://github.com/junegunn/jdbc-helper"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "A JDBC helper for JRuby/Database developers."
  s.test_files = [
    "test/database.yml",
    "test/database.yml.local",
    "test/helper.rb",
    "test/performance.rb",
    "test/test_connection.rb",
    "test/test_connectors.rb",
    "test/test_object_wrapper.rb",
    "test/test_sql.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<insensitive_hash>, ["~> 0.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, ["~> 0.9"])
      s.add_development_dependency(%q<test-unit>, [">= 2.3.0"])
    else
      s.add_dependency(%q<insensitive_hash>, ["~> 0.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, ["~> 0.9"])
      s.add_dependency(%q<test-unit>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<insensitive_hash>, ["~> 0.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, ["~> 0.9"])
    s.add_dependency(%q<test-unit>, [">= 2.3.0"])
  end
end

